---
title: "asies final"
author: "---"
date: "2024-06-27"
output: html_document
---

```{r}
install.packages("sf")
install.packages("ggplot2")
install.packages("RColorBrewer")  # Opcional, para la paleta de colores

```
```{r}
library(sf)
library(ggplot2)
library(RColorBrewer)  # Opcional

```

```{r}
theMapAndData <- st_read("C:/Users/USER/Workspace/TF_MAPS/FallecidosxProvincia.geojson")

```
```{r}
ggplot(data = theMapAndData) +
  geom_sf(aes(fill = Cantidad), color = "gray") +
  scale_fill_gradientn(colours = brewer.pal(9, "YlOrRd"), na.value = "white", name = "Cantidad") +
  theme_minimal() +
  ggtitle("Tasa de fallecidos por provincia (cien mil habitantes) - MAPA DE CALOR") +
  theme(plot.title = element_text(hjust = 0.5))

```
```{r}
install.packages("sf")
install.packages("ggplot2")

```

```{r}
library(sf)
library(ggplot2)
library(reticulate)
```

```{r}
# Importar los datos
fallecidos <- st_read("C:/Users/USER/Documents/ASIES_FINAL/mapitaNicoleEspacial.gpkg")

# Crear el mapa
ggplot(fallecidos) +
  geom_sf(aes(fill = FALLECIDOS_quadrant_names), color = "white", size = 0.1) +
  scale_fill_manual(values = c("ghostwhite", "red", "green", "black", "orange")) +
  theme_minimal() +
  theme(legend.position = c(-0.4, 0.5)) +
  ggtitle("Spots and Outliers")
```









